In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):

    def __init__(self,num_feature):

        super().__init__()
        self.linear=nn.Linear(num_feature,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, fetures):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

In [3]:
features = torch.rand(10,5)


In [4]:
model=Model(features.shape[1])

In [5]:
model(features)#it shows y_pred

tensor([[0.5926],
        [0.5391],
        [0.5241],
        [0.5809],
        [0.5666],
        [0.4989],
        [0.4535],
        [0.5576],
        [0.4977],
        [0.4545]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[-0.1560, -0.2273,  0.2940,  0.4162,  0.4331]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([-0.3026], requires_grad=True)

In [8]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [16]:
class hidden_nn(nn.Module):
     def __init__(self,num_feature):

        super().__init__()
        self.linear1=nn.Linear(num_feature,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

     def forward(self, fetures):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)

        return out

In [17]:
features = torch.rand(10,5)


In [18]:
model2=hidden_nn(features.shape[1])

In [19]:
model2(features)

tensor([[0.3736],
        [0.3834],
        [0.3914],
        [0.3871],
        [0.3903],
        [0.3763],
        [0.3886],
        [0.3916],
        [0.3854],
        [0.3805]], grad_fn=<SigmoidBackward0>)

In [20]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.4206, -0.2137, -0.2056,  0.3656,  0.2840],
        [ 0.1460,  0.0866, -0.0951,  0.0332, -0.2785],
        [-0.0885,  0.2420, -0.1081,  0.1357, -0.3639]], requires_grad=True)

In [21]:
from torchinfo import summary

summary(model2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
hidden_nn                                [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00