In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):

    def __init__(self,num_feature):

        super().__init__()
        self.linear=nn.Linear(num_feature,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, fetures):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

In [3]:
features = torch.rand(10,5)


In [4]:
model=Model(features.shape[1])

In [6]:
model(features)#it shows y_pred

tensor([[0.5583],
        [0.6341],
        [0.6387],
        [0.5920],
        [0.5880],
        [0.6810],
        [0.6505],
        [0.5563],
        [0.6095],
        [0.6429]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[ 0.3650, -0.1753,  0.1668, -0.0873, -0.0726]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([0.3713], requires_grad=True)

In [9]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00