In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):

    def __init__(self,num_feature):

        super().__init__()
        self.linear=nn.Linear(num_feature,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, fetures):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

In [4]:
features = torch.rand(10,5)


In [5]:
model=Model(features.shape[1])

In [6]:
model(features)#it shows y_pred

tensor([[0.3801],
        [0.3379],
        [0.4695],
        [0.4053],
        [0.5182],
        [0.4158],
        [0.4963],
        [0.5171],
        [0.4771],
        [0.4895]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[-0.4197,  0.1932, -0.1821,  0.3103,  0.2986]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([-0.3956], requires_grad=True)

In [9]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [10]:
class hidden_nn(nn.Module):
     def __init__(self,num_feature):

        super().__init__()
        self.linear1=nn.Linear(num_feature,3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

     def forward(self, fetures):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)

        return out

In [11]:
features = torch.rand(10,5)


In [12]:
model2=hidden_nn(features.shape[1])

In [13]:
model2(features)

tensor([[0.6253],
        [0.6024],
        [0.6258],
        [0.5926],
        [0.6272],
        [0.5851],
        [0.6290],
        [0.6236],
        [0.5809],
        [0.6270]], grad_fn=<SigmoidBackward0>)

In [14]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.2677,  0.2991,  0.2759,  0.1608,  0.0294],
        [ 0.3492,  0.1750, -0.2948,  0.1230,  0.1316],
        [ 0.2655, -0.3779, -0.0131,  0.4110, -0.2714]], requires_grad=True)

In [15]:
from torchinfo import summary

summary(model2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
hidden_nn                                [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [23]:
class Container(nn.Module):
     def __init__(self,num_feature):

        super().__init__()
        self.network=nn.Sequential(
                nn.Linear(num_feature,3),
                nn.ReLU(),
                nn.Linear(3,1),
                nn.Sigmoid()
        )

     def forward(self, fetures):
        out=self.network(features)
        return out

In [24]:
features = torch.rand(10,5)


In [25]:
features

tensor([[0.1803, 0.1588, 0.5256, 0.8799, 0.6339],
        [0.4752, 0.3579, 0.5830, 0.8570, 0.0713],
        [0.5905, 0.5111, 0.9097, 0.7829, 0.6339],
        [0.0989, 0.9257, 0.8497, 0.5878, 0.9263],
        [0.5043, 0.5866, 0.0648, 0.3270, 0.8598],
        [0.7008, 0.3059, 0.6591, 0.0046, 0.5432],
        [0.2321, 0.9433, 0.6461, 0.4404, 0.6253],
        [0.2693, 0.1318, 0.1347, 0.1808, 0.1659],
        [0.3132, 0.4271, 0.8092, 0.5224, 0.2293],
        [0.8216, 0.5835, 0.9479, 0.9306, 0.7203]])

In [26]:
model3=Container(features.shape[1])

In [29]:
model3(features)

tensor([[0.5271],
        [0.5426],
        [0.5233],
        [0.5369],
        [0.5547],
        [0.5441],
        [0.5529],
        [0.5643],
        [0.5428],
        [0.5164]], grad_fn=<SigmoidBackward0>)