In [1]:
import torch

In [3]:
#using empty
a=torch.empty(2,3)

In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand(2,3)

tensor([[0.7229, 0.0100, 0.6688],
        [0.2433, 0.2626, 0.1716]])

In [8]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.tensor([[1,2,3],
              [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [16]:
torch.full((3,3),2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [17]:
#Tensors shape
x=torch.tensor([[1,2,3],
              [4,5,6]])
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[4015157085744,             0,             0],
        [            0,             0,             0]])

In [19]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.rand_like(x , dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [22]:
#data types
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
x.dtype

torch.int64

In [24]:
torch.tensor([1.0,2.5,3.6] , dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [29]:
#maths operation
a=torch.rand(2,2)
a

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [30]:
a+2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [31]:
a-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [32]:
a*3

tensor([[0.6717, 0.9070],
        [0.5353, 2.4715]])

In [33]:
a/3

tensor([[0.0746, 0.1008],
        [0.0595, 0.2746]])

In [36]:
#int division
(a*100)//3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [37]:
((a*100)//3)%2

tensor([[1., 0.],
        [1., 1.]])

In [38]:
a**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

In [40]:
#element wise operation
p=torch.rand(2,3)
q=torch.rand(2,3)
print(p)
print(q)

tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])
tensor([[0.5163, 0.0359, 0.6476],
        [0.3430, 0.3182, 0.5261]])


In [41]:
p+q

tensor([[0.5332, 0.2568, 1.6012],
        [1.0494, 0.4811, 1.4163]])

In [42]:
p-q

tensor([[-0.4994,  0.1850,  0.3059],
        [ 0.3634, -0.1554,  0.3641]])

In [43]:
p*q

tensor([[0.0087, 0.0079, 0.6175],
        [0.2423, 0.0518, 0.4683]])

In [44]:
p/q

tensor([[0.0327, 6.1557, 1.4723],
        [2.0593, 0.5118, 1.6921]])

In [45]:
p**q

tensor([[0.1216, 0.9473, 0.9697],
        [0.8876, 0.5613, 0.9406]])

In [46]:
p%q

tensor([[0.0169, 0.0056, 0.3059],
        [0.0204, 0.1629, 0.3641]])

In [47]:
y=torch.tensor([1,-2,3,-4])

In [48]:
torch.abs(y)

tensor([1, 2, 3, 4])

In [49]:
torch.neg(y)

tensor([-1,  2, -3,  4])

In [59]:
z=torch.tensor([1.5,2.1,3.9,-4.5])

In [60]:
torch.round(z)

tensor([ 2.,  2.,  4., -4.])

In [61]:
torch.ceil(z)

tensor([ 2.,  3.,  4., -4.])

In [62]:
torch.floor(z)

tensor([ 1.,  2.,  3., -5.])

In [63]:
torch.clamp(z,min=2,max=3)

tensor([2.0000, 2.1000, 3.0000, 2.0000])

In [71]:
#reduction operation
c=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [72]:
c

tensor([[2., 6., 7.],
        [7., 8., 3.]])

In [73]:
torch.sum(c)

tensor(33.)

In [74]:
torch.sum(c,dim=0) 

tensor([ 9., 14., 10.])

In [75]:
torch.sum(c,dim=1) 

tensor([15., 18.])

In [76]:
torch.mean(c)

tensor(5.5000)

In [77]:
torch.mean(c,dim=0)

tensor([4.5000, 7.0000, 5.0000])

In [78]:
torch.mean(c,dim=1)

tensor([5., 6.])

In [80]:
torch.median(c)

tensor(6.)

In [81]:
torch.min(c)

tensor(2.)

In [82]:
torch.max(c)

tensor(8.)

In [83]:
torch.prod(c)

tensor(14112.)

In [84]:
torch.std(c)

tensor(2.4290)

In [86]:
torch.var(c)

tensor(5.9000)

In [87]:
torch.argmax(c)

tensor(4)

In [88]:
torch.argmin(c)

tensor(0)

In [93]:
#matrix multiplication
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.randint(size=(3,2),low=0,high=10)

In [94]:
a

tensor([[0, 6, 4],
        [0, 8, 4]])

In [95]:
b

tensor([[7, 2],
        [3, 8],
        [5, 6]])

In [96]:
torch.matmul(a,b)

tensor([[38, 72],
        [44, 88]])

In [97]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [98]:
#transpose
torch.transpose(a,0,1)

tensor([[0, 0],
        [6, 8],
        [4, 4]])

In [99]:
#determinant
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 9., 5.],
        [0., 4., 2.],
        [7., 1., 1.]])

In [100]:
torch.det(h)

tensor(-10.0000)

In [102]:
#inverse
torch.inverse(h)

tensor([[-0.2000,  0.4000,  0.2000],
        [-1.4000,  3.3000,  0.4000],
        [ 2.8000, -6.1000, -0.8000]])

In [103]:
#comparision operations
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 4, 4],
        [1, 1, 2]])
tensor([[4, 7, 2],
        [5, 6, 1]])


In [104]:
i>j

tensor([[ True, False,  True],
        [False, False,  True]])

In [105]:
i<j

tensor([[False,  True, False],
        [ True,  True, False]])

In [106]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [107]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [109]:
i<=j

tensor([[False,  True, False],
        [ True,  True, False]])

In [110]:
i>=j

tensor([[ True, False,  True],
        [False, False,  True]])

In [111]:
#special function
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 5., 6.],
        [9., 2., 3.]])

In [112]:
torch.log(k)

tensor([[1.3863, 1.6094, 1.7918],
        [2.1972, 0.6931, 1.0986]])

In [113]:
torch.exp(k)

tensor([[5.4598e+01, 1.4841e+02, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.0086e+01]])

In [114]:
torch.sqrt(k)

tensor([[2.0000, 2.2361, 2.4495],
        [3.0000, 1.4142, 1.7321]])

In [115]:
torch.sigmoid(k)

tensor([[0.9820, 0.9933, 0.9975],
        [0.9999, 0.8808, 0.9526]])

In [116]:
torch.softmax(k,dim=0)

tensor([[0.0067, 0.9526, 0.9526],
        [0.9933, 0.0474, 0.0474]])

In [117]:
torch.relu(k)

tensor([[4., 5., 6.],
        [9., 2., 3.]])

In [118]:
#inplace operations
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])
tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])
