In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
X = torch.tensor([[1,1],
                  [1,0],
                  [0,1],
                  [0,0]], dtype=torch.float32)

Y = torch.tensor([[0],
                  [1],
                  [1],
                  [0]], dtype=torch.float32)

In [3]:
X.shape

torch.Size([4, 2])

In [4]:
Y.shape

torch.Size([4, 1])

In [5]:
#model
model = nn.Sequential(
    nn.Linear(2, 4),   # Input layer -> Hidden layer
    nn.ReLU(),
    nn.Linear(4, 1)    # Hidden layer -> Output layer
)

In [6]:
loss_fn = nn.BCEWithLogitsLoss()

In [7]:
optimizer = optim.Adam(
    model.parameters(),
    lr=0.01
)

In [9]:
# TRAINING LOOP
epochs=2000
for epoch in range(epochs):
    #forward pass
    logits=model(X)
    #loss
    cost=loss_fn(logits,Y)
    #clear old grad
    optimizer.zero_grad()
    #backward pass
    cost.backward()
    #update
    optimizer.step()
    if epoch % 500 == 0:
        print(f"Epoch {epoch} | Loss = {cost.item():.6f}")

Epoch 0 | Loss = 0.683693
Epoch 500 | Loss = 0.027563
Epoch 1000 | Loss = 0.005840
Epoch 1500 | Loss = 0.002412


In [12]:
for name, param in model.named_parameters():
    print(name)
    print(param)
    print("shape:", param.shape)
    print("------")

0.weight
Parameter containing:
tensor([[-0.4219, -0.3975],
        [-4.6228,  4.6228],
        [-2.1064,  2.1543],
        [-0.1218, -0.0285]], requires_grad=True)
shape: torch.Size([4, 2])
------
0.bias
Parameter containing:
tensor([-1.1561e-02,  1.1518e-04,  2.1064e+00, -3.9043e-01],
       requires_grad=True)
shape: torch.Size([4])
------
2.weight
Parameter containing:
tensor([[ 0.4024,  5.8121, -6.1319,  0.1444]], requires_grad=True)
shape: torch.Size([1, 4])
------
2.bias
Parameter containing:
tensor([6.2388], requires_grad=True)
shape: torch.Size([1])
------


In [13]:
#prediction
with torch.no_grad():

    logits = model(X)

    probs = torch.sigmoid(logits)

    predictions = (probs > 0.5).int()

    print("\nProbabilities:")
    print(probs)

    print("\nPredictions:")
    print(predictions)

    print("\nActual:")
    print(Y.int())


Probabilities:
tensor([[9.3837e-04],
        [9.9805e-01],
        [9.9907e-01],
        [1.2585e-03]])

Predictions:
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)

Actual:
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)
