In [30]:
import torch
import torch.nn as nn
import torch.optim as optim

In [31]:
X=torch.tensor([[1,1],
                [1,0],
                [0,1],
                [0,0]] ,dtype=torch.float32)
Y=torch.tensor([[0],
                [1],
                [1],
                [0]] ,dtype=torch.float32)
print(X.shape)
print(Y.shape)

torch.Size([4, 2])
torch.Size([4, 1])


In [32]:
class NeuralNetwork(nn.Module):

    def __init__(self):
         super().__init__()

         self.fc1=nn.Linear(2,4)
         self.fc2=nn.Linear(4,1)
        
    def forward(self, x):
         x=self.fc1(x)
         x=torch.relu(x)
         x=self.fc2(x)
         x=torch.sigmoid(x)
        
         return x

In [33]:
model=NeuralNetwork()
print(model)

NeuralNetwork(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


In [34]:
model=NeuralNetwork()
output=model(X)
print(output)
print(output.shape)

tensor([[0.5978],
        [0.6624],
        [0.5786],
        [0.6425]], grad_fn=<SigmoidBackward0>)
torch.Size([4, 1])


In [35]:
loss=nn.BCELoss()

In [36]:
cost=loss(output,Y)
print(cost)

tensor(0.7246, grad_fn=<BinaryCrossEntropyBackward0>)


In [37]:
optimizer=optim.Adam(
    model.parameters(),
    lr=0.1
)

In [38]:
for name , param in model.named_parameters():
    print(name)
    print(param)
    print("shape:", param.shape)
    print("------")

fc1.weight
Parameter containing:
tensor([[-0.3177,  0.1659],
        [-0.1348,  0.3885],
        [ 0.5716,  0.5964],
        [ 0.3871, -0.5708]], requires_grad=True)
shape: torch.Size([4, 2])
------
fc1.bias
Parameter containing:
tensor([ 0.3018,  0.3707, -0.0689,  0.5954], requires_grad=True)
shape: torch.Size([4])
------
fc2.weight
Parameter containing:
tensor([[-0.2378,  0.1404, -0.1830,  0.3287]], requires_grad=True)
shape: torch.Size([1, 4])
------
fc2.bias
Parameter containing:
tensor([0.4101], requires_grad=True)
shape: torch.Size([1])
------


In [39]:
epochs=2000
for epoch in range(epochs):
    output=model(X)
    cost=loss(output,Y)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 500 == 0:
        print(f"Epoch {epoch} | Loss = {cost.item():.6f}")

Epoch 0 | Loss = 0.724568
Epoch 500 | Loss = 0.000487
Epoch 1000 | Loss = 0.000158
Epoch 1500 | Loss = 0.000078


In [40]:
with torch.no_grad():
    output=model(X)
    
    prediction=(output>0.5).int()

    print("Probabilities:")
    print(output)

    print("\nPredictions:")
    print(prediction)

    print("\nActual:")
    print(Y)

    correct=(prediction == Y).int().sum()
    print(correct)
    accuracy=correct/Y.shape[0]
    print("accuracy is : " , accuracy.item()*100 ,"%")

Probabilities:
tensor([[1.0198e-05],
        [9.9999e-01],
        [9.9984e-01],
        [1.0313e-05]])

Predictions:
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)

Actual:
tensor([[0.],
        [1.],
        [1.],
        [0.]])
tensor(4)
accuracy is :  100.0 %
