In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [3]:
X=torch.tensor([[1,1],
                [1,0],
                [0,1],
                [0,0]] ,dtype=torch.float32)
Y=torch.tensor([[0],
                [1],
                [1],
                [0]] ,dtype=torch.float32)
print(X.shape)
print(Y.shape)

torch.Size([4, 2])
torch.Size([4, 1])


In [10]:
class NeuralNetwork(nn.Module):

    def __init__(self):
         super().__init__()

         self.fc1=nn.Linear(2,4)
         self.fc2=nn.Linear(4,1)
        
    def forward(self, x):
         x=self.fc1(x)
         x=torch.relu(x)
         x=self.fc2(x)
         x=torch.sigmoid(x)
        
         return x

In [11]:
model=NeuralNetwork()
print(model)

NeuralNetwork(
  (fc1): Linear(in_features=2, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=1, bias=True)
)


In [13]:
model=NeuralNetwork()
output=model(X)
print(output)
print(output.shape)

tensor([[0.4390],
        [0.4492],
        [0.4385],
        [0.4674]], grad_fn=<SigmoidBackward0>)
torch.Size([4, 1])


In [14]:
loss=nn.BCELoss()

In [15]:
cost=loss(output,Y)
print(cost)

tensor(0.7081, grad_fn=<BinaryCrossEntropyBackward0>)


In [18]:
optimizer=optim.Adam(
    model.parameters(),
    lr=0.1
)

In [21]:
for name , param in model.named_parameters():
    print(name)
    print(param)
    print("shape:", param.shape)
    print("------")

fc1.weight
Parameter containing:
tensor([[-0.0622, -0.4582],
        [ 0.5661,  0.5099],
        [ 0.5838,  0.4733],
        [ 0.0391,  0.0308]], requires_grad=True)
shape: torch.Size([4, 2])
------
fc1.bias
Parameter containing:
tensor([ 0.1510,  0.1900, -0.1992,  0.3456], requires_grad=True)
shape: torch.Size([4])
------
fc2.weight
Parameter containing:
tensor([[ 0.3057, -0.3087,  0.2816,  0.3174]], requires_grad=True)
shape: torch.Size([1, 4])
------
fc2.bias
Parameter containing:
tensor([-0.2279], requires_grad=True)
shape: torch.Size([1])
------


In [22]:
optimizer.zero_grad()
epochs=2000
for epoch in range(epochs):
    #forward pass
    logits=model(X)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch % 500 == 0:
        print(f"Epoch {epoch} | Loss = {cost.item():.6f}")

In [27]:
with torch.no_grad():
    output=model(X)
    
    prediction=(output>0.5).int()

    print("Probabilities:")
    print(output)

    print("\nPredictions:")
    print(prediction)

    print("\nActual:")
    print(Y)

    correct=(prediction == Y).int().sum()
    print(correct)
    accuracy=correct/Y.shape[0]
    print("accuracy is : " , accuracy.item()*100 ,"%")

Probabilities:
tensor([[0.5447],
        [0.5413],
        [0.5236],
        [0.5227]])

Predictions:
tensor([[1],
        [1],
        [1],
        [1]], dtype=torch.int32)

Actual:
tensor([[0.],
        [1.],
        [1.],
        [0.]])
tensor(2)
accuracy is :  50.0 %
