In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

In [3]:
X = torch.tensor([[1,1],
                  [1,0],
                  [0,1],
                  [0,0]], dtype=torch.float32)#4 examples hain Har example mein 2 features hain

Y = torch.tensor([[0],
                  [1],
                  [1],
                  [0]], dtype=torch.float32)#float kyuki PyTorch ke nn.Linear layer ke weights FloatTensor hote hain,

In [4]:
X.shape

torch.Size([4, 2])

In [5]:
Y.shape

torch.Size([4, 1])

In [6]:
#model
model = nn.Sequential(
    nn.Linear(2, 4),   # Input layer -> Hidden layer
    nn.ReLU(),
    nn.Linear(4, 1)    # Hidden layer -> Output layer
)

In [7]:
loss_fn = nn.BCEWithLogitsLoss()

In [8]:
optimizer = optim.Adam(
    model.parameters(),
    lr=0.01
)

In [9]:
# TRAINING LOOP
epochs=2000
for epoch in range(epochs):
    #forward pass
    logits=model(X)
    #loss
    cost=loss_fn(logits,Y)
    #clear old grad
    optimizer.zero_grad()
    #backward pass
    cost.backward()
    #update
    optimizer.step()
    if epoch % 500 == 0:
        print(f"Epoch {epoch} | Loss = {cost.item():.6f}")

Epoch 0 | Loss = 0.730391
Epoch 500 | Loss = 0.026342
Epoch 1000 | Loss = 0.006665
Epoch 1500 | Loss = 0.003027


In [10]:
for name, param in model.named_parameters():
    print(name)
    print(param)
    print("shape:", param.shape)
    print("------")

0.weight
Parameter containing:
tensor([[-0.1095,  0.1901],
        [ 2.1941,  2.1938],
        [-1.9012, -1.9012],
        [-2.1863, -2.1845]], requires_grad=True)
shape: torch.Size([4, 2])
------
0.bias
Parameter containing:
tensor([-0.2241, -2.1939,  1.9013,  2.1834], requires_grad=True)
shape: torch.Size([4])
------
2.weight
Parameter containing:
tensor([[-0.0883, -5.8813, -3.4018, -3.4479]], requires_grad=True)
shape: torch.Size([1, 4])
------
2.bias
Parameter containing:
tensor([5.8775], requires_grad=True)
shape: torch.Size([1])
------


In [11]:
#prediction
with torch.no_grad():

    logits = model(X)

    probs = torch.sigmoid(logits)

    predictions = (probs > 0.5).int()

    print("\nProbabilities:")
    print(probs)

    print("\nPredictions:")
    print(predictions)

    print("\nActual:")
    print(Y.int())


Probabilities:
tensor([[8.8787e-04],
        [9.9720e-01],
        [9.9721e-01],
        [2.9798e-04]])

Predictions:
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)

Actual:
tensor([[0],
        [1],
        [1],
        [0]], dtype=torch.int32)
